#!/usr/bin/env node

/**
 * ATMOS Development Setup Script
 * 
 * This script helps configure the frontend to work with your deployed smart contracts.
 * It will:
 * 1. Check if contracts are deployed
 * 2. Extract contract addresses
 * 3. Update the contracts.ts configuration file
 * 4. Create/update .env.local
 */

const fs = require('fs');
const path = require('path');

console.log('🚀 ATMOS Development Setup\n');

// Paths
const rootDir = path.resolve(__dirname, '../..');
const frontendDir = path.resolve(__dirname, '..');
const contractsConfigPath = path.join(frontendDir, 'src/config/contracts.ts');
const envLocalPath = path.join(frontendDir, '.env.local');
const envExamplePath = path.join(frontendDir, '.env.example');

// Check if running from correct directory
if (!fs.existsSync(contractsConfigPath)) {
  console.error('❌ Error: Could not find contracts.ts');
  console.error('   Make sure you\'re running this from the frontend directory');
  process.exit(1);
}

console.log('📁 Project structure detected:');
console.log(`   Root: ${rootDir}`);
console.log(`   Frontend: ${frontendDir}\n`);

// Function to find deployment artifacts
function findDeploymentAddresses() {
  const artifactsPath = path.join(rootDir, 'deployments');
  const addresses = {
    carbonCreditNFT: null,
    carbonMarketplace: null,
    carbonPriceOracle: null,
    emissionVerifier: null,
  };

  if (!fs.existsSync(artifactsPath)) {
    console.log('ℹ️  No deployments folder found. Using default addresses.\n');
    return null;
  }

  // Try to find network folders
  const networks = fs.readdirSync(artifactsPath).filter(f => 
    fs.statSync(path.join(artifactsPath, f)).isDirectory()
  );

  if (networks.length === 0) {
    console.log('ℹ️  No deployment networks found. Using default addresses.\n');
    return null;
  }

  // Use the first network found (usually 'localhost' or 'mumbai')
  const network = networks[0];
  console.log(`📡 Found deployment on network: ${network}`);

  const networkPath = path.join(artifactsPath, network);
  
  // Look for contract JSON files
  const files = fs.readdirSync(networkPath);
  
  files.forEach(file => {
    if (!file.endsWith('.json')) return;
    
    try {
      const content = JSON.parse(fs.readFileSync(path.join(networkPath, file), 'utf8'));
      if (content.address) {
        if (file.includes('CarbonCreditNFT')) {
          addresses.carbonCreditNFT = content.address;
        } else if (file.includes('CarbonMarketplace')) {
          addresses.carbonMarketplace = content.address;
        } else if (file.includes('CarbonPriceOracle')) {
          addresses.carbonPriceOracle = content.address;
        } else if (file.includes('EmissionVerifier')) {
          addresses.emissionVerifier = content.address;
        }
      }
    } catch (e) {
      // Skip invalid JSON files
    }
  });

  return addresses;
}

// Default addresses for Hardhat local network
const DEFAULT_ADDRESSES = {
  carbonCreditNFT: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
  carbonMarketplace: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
  carbonPriceOracle: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
  emissionVerifier: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
};

// Get addresses
const deployedAddresses = findDeploymentAddresses();
const addresses = deployedAddresses || DEFAULT_ADDRESSES;

console.log('\n📝 Contract Addresses:');
console.log(`   CarbonCreditNFT:    ${addresses.carbonCreditNFT}`);
console.log(`   CarbonMarketplace:  ${addresses.carbonMarketplace}`);
console.log(`   CarbonPriceOracle:  ${addresses.carbonPriceOracle}`);
console.log(`   EmissionVerifier:   ${addresses.emissionVerifier}\n`);

// Update contracts.ts
console.log('📄 Updating src/config/contracts.ts...');

const contractsContent = `// Auto-generated by setup-dev.js
// Run 'npm run setup' to regenerate this file with deployed contract addresses

export const CONTRACTS = {
  CARBON_CREDIT_NFT: '${addresses.carbonCreditNFT}' as \`0x\${string}\`,
  CARBON_MARKETPLACE: '${addresses.carbonMarketplace}' as \`0x\${string}\`,
  CARBON_PRICE_ORACLE: '${addresses.carbonPriceOracle}' as \`0x\${string}\`,
  EMISSION_VERIFIER: '${addresses.emissionVerifier}' as \`0x\${string}\`,
};

// Minimal ABIs for contract interactions
export const ABI_CARBON_CREDIT_NFT = [
  'function mintCredit(uint256 tonnes, uint256 expiryDate) public returns (uint256)',
  'function retireCredit(uint256 tokenId, uint256 amount) public',
  'function balanceOf(address owner) view returns (uint256)',
  'function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)',
  'function getCreditDetails(uint256 tokenId) view returns (address creator, uint256 tonnes, uint256 expiryDate, bool retired)',
  'event CreditMinted(address indexed creator, uint256 indexed tokenId, uint256 tonnes)',
  'event CreditRetired(address indexed retiree, uint256 indexed tokenId, uint256 amount)',
] as const;

export const ABI_CARBON_MARKETPLACE = [
  'function createOrder(uint256 creditId, uint256 amount, uint256 price, bool isBuy) public returns (uint256 orderId)',
  'function executeOrder(uint256 orderId) public payable',
  'function cancelOrder(uint256 orderId) public',
  'event OrderCreated(uint256 indexed orderId, address indexed creator, uint256 creditId, uint256 amount, uint256 price, bool isBuy)',
  'event OrderExecuted(uint256 indexed orderId, address indexed buyer, address indexed seller, uint256 amount, uint256 price)',
] as const;

export const ABI_CARBON_PRICE_ORACLE = [
  'function getLatestPrice() view returns (uint256)',
  'function updatePrice(uint256 newPrice) public',
] as const;

export const ABI_EMISSION_VERIFIER = [
  'function getEmissionData(address company) view returns (uint256 scope1, uint256 scope2, uint256 scope3, uint256 totalTarget)',
  'function updateEmissions(address company, uint256 scope1, uint256 scope2, uint256 scope3) public',
] as const;
`;

fs.writeFileSync(contractsConfigPath, contractsContent);
console.log('   ✅ Updated contracts.ts\n');

// Create .env.local if it doesn't exist
if (!fs.existsSync(envLocalPath)) {
  console.log('📄 Creating .env.local...');
  
  const envContent = `# Auto-generated by setup-dev.js
# Network Configuration
NEXT_PUBLIC_NETWORK=hardhat
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545

# Contract Addresses
NEXT_PUBLIC_CARBON CREDIT_NFT=${addresses.carbonCreditNFT}
NEXT_PUBLIC_CARBON_MARKETPLACE=${addresses.carbonMarketplace}
NEXT_PUBLIC_CARBON_PRICE_ORACLE=${addresses.carbonPriceOracle}
NEXT_PUBLIC_EMISSION_VERIFIER=${addresses.emissionVerifier}

# WalletConnect Project ID
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=demo-project-id
`;

  fs.writeFileSync(envLocalPath, envContent);
  console.log('   ✅ Created .env.local\n');
} else {
  console.log('ℹ️  .env.local already exists. Skipping.\n');
}

console.log('✨ Setup complete!\n');
console.log('📋 Next steps:');
console.log('   1. Make sure Hardhat node is running: npx hardhat node');
console.log('   2. Deploy contracts if not already: npx hardhat run scripts/deploy/01_deploy_local.js --network localhost');
console.log('   3. Start the dev server: npm run dev');
console.log('   4. Connect MetaMask to http://localhost:8545');
console.log('   5. Import a test account from Hardhat output\n');
console.log('🌐 Visit http://localhost:3001 to see your app!\n');
